# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rprogressbardemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import time

from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtGui import QBrush, QColor, QPalette
from PyQt5.QtWidgets import QApplication, qApp

from qroundprogressbar import QRoundProgressBar
from threading import Timer
from PyQt5 import QtCore, QtGui, QtWidgets
from random import random


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: #1f1b24;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(190, 140, 441, 311))
        self.groupBox.setStyleSheet("\n"
            "border-radius:30px;\n"
"background-color: #121212;\n"
"border : 0px;\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")    
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 19, 401, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.progress = QRoundProgressBar()
        self.progress.setBarStyle(QRoundProgressBar.BarStyle.LINE)
        self.progress.setDecimals(1)
        self.progress.setFormat('%v')
        self.progress.setOutlinePenWidth(3)
        self.progress.setDataPenWidth(3)
        self.progress.setNullPosition(QRoundProgressBar.PositionBottom)
        self.progress.setRange(-40,40)
        self.progress.setValue(23)
         # style accordingly via palette
        palette = QPalette()
        palette.setBrush(QPalette.AlternateBase, QColor('#121212'))
        palette.setBrush(QPalette.Highlight, QColor('#d4f542'))
        palette.setColor(QPalette.Text, Qt.white)
        self.progress.setPalette(palette)
        self.gridLayout.addWidget(self.progress,0,1)

        self.progress2 = QRoundProgressBar()
        self.progress2.setBarStyle(QRoundProgressBar.BarStyle.LINE)
        self.progress2.setDecimals(1)
        self.progress2.setFormat('%v')
        self.progress2.setOutlinePenWidth(3)
        self.progress2.setDataPenWidth(3)
        self.progress2.setNullPosition(QRoundProgressBar.PositionBottom)
        gradientPoints2 = [(0, QColor('#42f554'))]
        self.progress2.setDataColors(gradientPoints2)
        self.progress2.setRange(-40,40)
        self.progress2.setValue(21)
         # style accordingly via palette
        palette2 = QPalette()
        palette2.setBrush(QPalette.AlternateBase, QColor('#121212'))
        palette2.setBrush(QPalette.Highlight, QColor('#42f5e3'))
        palette2.setColor(QPalette.Text, Qt.white)
        self.progress2.setPalette(palette2)
        self.gridLayout.addWidget(self.progress2,0,2)

        self.progress3 = QRoundProgressBar()
        self.progress3.setBarStyle(QRoundProgressBar.BarStyle.LINE)
        self.progress3.setDecimals(1)
        self.progress3.setFormat('%v')
        self.progress2.setOutlinePenWidth(3)
        self.progress3.setDataPenWidth(3)
        self.progress3.setNullPosition(QRoundProgressBar.PositionBottom)
        gradientPoints3 = [(0, QColor('#426ff5'))]
        self.progress3.setDataColors(gradientPoints3)
        self.progress3.setRange(-40,40)
        self.progress3.setValue(15)
         # style accordingly via palette
        palette3 = QPalette()
        palette3.setBrush(QPalette.AlternateBase, QColor('#121212'))
        palette3.setBrush(QPalette.Highlight, QColor('#7e42f5'))
        palette3.setColor(QPalette.Text, Qt.white)
        self.progress3.setPalette(palette3)
        self.gridLayout.addWidget(self.progress3,0,3)

        self.progress4 = QRoundProgressBar()
        self.progress4.setBarStyle(QRoundProgressBar.BarStyle.LINE)
        self.progress4.setDecimals(1)
        self.progress4.setFormat('%v')
        self.progress4.setOutlinePenWidth(3)
        self.progress4.setDataPenWidth(3)
        self.progress4.setNullPosition(QRoundProgressBar.PositionBottom)
        self.progress4.setRange(-40,40)
        self.progress4.setValue(-4)
         # style accordingly via palette
        palette4 = QPalette()
        palette4.setBrush(QPalette.AlternateBase, QColor('#121212'))
        palette4.setBrush(QPalette.Highlight, QColor('#f542f2'))
        palette4.setColor(QPalette.Text, Qt.white)
        self.progress4.setPalette(palette4)
        self.gridLayout.addWidget(self.progress4,1,1)

        self.progress5 = QRoundProgressBar()
        self.progress5.setBarStyle(QRoundProgressBar.BarStyle.LINE)
        self.progress5.setDecimals(1)
        self.progress5.setFormat('%v')
        self.progress5.setOutlinePenWidth(3)
        self.progress5.setDataPenWidth(3)
        self.progress5.setNullPosition(QRoundProgressBar.PositionBottom)
        self.progress5.setRange(-40,40)
        self.progress5.setValue(-30)
         # style accordingly via palette
        palette5 = QPalette()
        palette5.setBrush(QPalette.AlternateBase, QColor('#121212'))
        palette5.setBrush(QPalette.Highlight, QColor('#f5427e'))
        palette5.setColor(QPalette.Text, Qt.white)
        self.progress5.setPalette(palette5)
        self.gridLayout.addWidget(self.progress5,1,2)

        self.progress6 = QRoundProgressBar()
        self.progress6.setBarStyle(QRoundProgressBar.BarStyle.LINE)
        self.progress6.setDecimals(1)
        self.progress6.setFormat('%v')
        self.progress6.setOutlinePenWidth(3)
        self.progress6.setDataPenWidth(3)
        self.progress6.setNullPosition(QRoundProgressBar.PositionBottom)
        self.progress6.setRange(-40,40)
        self.progress6.setValue(35)
         # style accordingly via palette
        palette6 = QPalette()
        palette6.setBrush(QPalette.AlternateBase, QColor('#121212'))
        palette6.setBrush(QPalette.Highlight, QColor('#f57e42'))
        palette6.setColor(QPalette.Text, Qt.white)
        self.progress6.setPalette(palette6)
        self.gridLayout.addWidget(self.progress6,1,3)






        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.timer = QTimer()
        self.timer.setInterval(5000)
        self.timer.timeout.connect(self.updateBar)
        self.timer.start()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def updateBar(self):
       
        self.progress.setValue((random()*40)-20)
        self.progress2.setValue((random()*40)-20)
        self.progress3.setValue((random()*40)-20)
        self.progress4.setValue((random()*40)-20)
        self.progress5.setValue((random()*40)-20)
        self.progress6.setValue((random()*40)-20)
        
       


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
